### ISSUE TITLE
Missing adfs_default_username causes exception

### ISSUE THREAD

**Issue by alblue** [NitorCreations/adfs-aws-login#4]
When running without a default username in `adfs_default_username`, a crash occurs:

```
Traceback (most recent call last):
  File "/usr/local/bin/adfs-aws-login", line 10, in <module>
    sys.exit(adfs_aws_login())
  File "/Library/Python/3.8/site-packages/adfs_aws_login/cli.py", line 20, in adfs_aws_login
    sys.stdout.write("Username [" + conf.DEFAULT_USERNAME + "]: ")
TypeError: can only concatenate str (not "NoneType") to str
```

It would be useful if the value was missing for it to default to an empty string, so the user can type in their own value.

**Comment by psiniemi** [comment]
Closed with PR #5
